Traceback (most recent call last):
  File "/var/folders/10/yz_54qpj0x9bty53l23kctwc0000gp/T/ipykernel_91912/4138097472.py", line 11, in train
    model.fit(X_train, y_train, early_stopping_rounds=10, eval_set=[(X_val, y_val)], verbose=False)
  File "/Users/wpw555/miniconda3/envs/kaggle-env/lib/python3.9/site-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
TypeError: fit() got an unexpected keyword argument 'early_stopping_rounds'
